### ISSUE TITLE
Unclear required dependencies

### ISSUE THREAD

**Issue by MarketaAdamova** [xsc/kithara#5]
Hi,
I have a question about some libraries which are required for using kithara but there is no notes about this in README.

**com.rabbitmq/amqp-client**
This is ok, I see why should be provided. But maybe a comment in README would help to clarify (also did not work with older version of amqp-client I originally had in my computer - sorry can't remember the exact version anymore).

**org.slf4j/slf4j-log4j12**
This is defined as dependency for dev profile but unless I import it separately, SLF4J will default to a no-operation implementation and I only get warning message.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Again if expected to be present maybe a note should be added to README?

Thanks
  Marketa

**Comment by xsc** [comment]
@MarketaAdamova I actually never intended to not have `com.rabbitmq/amqp-client` included - I expected the transitive one from Lyra to be used but seems I misunderstood the `provided` scope and never verified that the client was really there... :-/

Regarding `org.slf4j/slf4j-log4j12`, I'll add a note that this library uses SLF4J-compliant logging so an actual logging dependency needs to be included. (It's not "expected to be present" per se, since kithara will work without it just as well.)

**Comment by MarketaAdamova** [comment]
Hi,
the Lyra version you are using has this dependency.

`<dependencies>
    <dependency>
      <groupId>com.rabbitmq</groupId>
      <artifactId>amqp-client</artifactId>
      <version>3.5.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.5</version>
    </dependency>
`
It has  only provided scope as well but also you need newer version for kithara code (I think :)

**Comment by xsc** [comment]
`com.rabbitmq/amqp-client` is now included directly and I added a note to the README about logging. FWIW, the kithara tests seem to pass with version 3.5.3 as well. :)

``` clojure
[kithara "0.1.3"]
```
